version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:2.35.0
    container_name: wiremock
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command: ["--global-response-templating"]